### ISSUE TITLE
Тут все ок, но можно посмотреть на generic для функции, вместо any

### ISSUE THREAD

**Issue by TakeYouWanna** [degtyarev-rrr/algorithmic-tasks#1]
https://github.com/degtyarev-rrr/algorithmic-tasks/blob/467de5cbce474feff5e1d379465a4254bf535911/index.ts#L14

**Comment by degtyarev-rrr** [comment]
да я хотел через них сделать, но подумал, что в массиве одновременно могут быть разные типы и  поэтому решил, что их неудобно тут юзать
