### ISSUE TITLE
Тут нужно возвращать true по условию

### ISSUE THREAD

**Issue by TakeYouWanna** [degtyarev-rrr/algorithmic-tasks#2]
https://github.com/degtyarev-rrr/algorithmic-tasks/blob/467de5cbce474feff5e1d379465a4254bf535911/index.ts#L16

**Comment by TakeYouWanna** [comment]
// Если колбек-функция не была передана, то из any возвращаем true,

**Comment by degtyarev-rrr** [comment]
Не, тут по условию не так чуть-чуть. Просто из-за добавления комментариев в несколько строк  условие имеет нечитабельный вид и суть немного потерялась. 
"Если колбек-функция не была передана, то из any возвращаем true,  если в массиве есть хотя бы один элемент, который дает true,  если все значения в массиве дают false, то возвращаем false"
